# -*- coding: utf-8 -*-
"""GammarCorrection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwmmOflhSSt7-YpOriEwOh8HhNn79CsN
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
model_name = "vennify/t5-base-grammar-correction"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

input_text = "She go to school every day and study very hardly."

input_ids = tokenizer.encode(
    "grammar: " + input_text,
    return_tensors="pt",
    max_length=128,
    truncation=True
).to(device)

outputs = model.generate(input_ids, max_length=128)
corrected_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("Original Sentence:", input_text)
print("Corrected Sentence:", corrected_text)

